### PR TITLE
Add taproot support

### PR DESCRIPTION
**Pull request by nerolation**
Add Bech32m encoding/decoding for taproot addresses. The decoding was written by Pieter Wuille here: https://github.com/Bytom/python-bytomlib/blob/master/pybtmsdk/segwit_addr.py

The check if a PkScript represents an Bech32m script is done in the following:
* The script must start with 0x01
* The second part of the script must result in a valid taproot address when encoded

Notably, the check for Taproot is the last check before a script would be classifies as unknown, thus avoiding useless computation for checking if a tweaked public key might be encoded into a valid address.

Everything was squashed into one commit.

### CODE REVIEW

**Comment by Nerolation** [comment]
Hi @alecalve ,
If you want me to provide further material (e.g. tests or test blk.dat files) I'm happy to help.

**Comment by alecalve** [comment]
Thanks for your contribution, I think some tests would be warranted yes

**Comment by Nerolation** [comment]
> Thanks for your contribution, I think some tests would be warranted yes

Fine, I will attach some!
Best!

**Comment by Nerolation** [comment]
Hi @alecalve !
I verified some transactions that I took from here https://bitcoin.stackexchange.com/questions/110995/how-can-i-find-samples-for-p2tr-transactions-on-mainnet
I put it into the tests folder.
Works fine!
Best!

**Comment by Nerolation** [comment]
Ready to rumble @alecalve

**Comment by Nerolation** [comment]
It's a pity this one isn't merged @alecalve

**Pull request merged**
