### PR TITLE
Add protections to not attempt to parse new blocks before they are ready

### PR DESCRIPTION
**Pull request by brannondorsey**
Parsing the very latest blocks, `get_ordered_blocks(...)` error with block indexes having values `-1` for `index.file` and `index.data_pos`. This will result in an `Error: file not found.` error. Add a check to prevent this from happening. I'm not entirely sure why this is, but it only seems to happen for the very top 1-3 blocks that were received by a live running node (perhaps because they are so new and haven't been confirmed?). These `-1` values are being set [here](https://github.com/brangerbriz/python-bitcoin-blockchain-parser/blob/master/blockchain_parser/index.py#L39-L49).

### CODE REVIEW

**Comment by alecalve** [comment]
Wouldn't it make sense to break out of the for loop when encountering a such case? Otherwise we could be skipping blocks.

**Comment by brannondorsey** [comment]
Sounds good, I've made the appropriate changes. 

Separately, I'm trying to wrap my head around what is causing this condition to be true in the first place. It appears to occur when a block is present in bitcoind's leveldb index but not yet stored in a `.dat` file. Not that it is an error, more that I haven't quite groked the condition that leads to this. 

It is obviously a situation that is accounted for in the Bitcoin Core [source code](https://github.com/bitcoin/bitcoin/blob/5961b23898ee7c0af2626c46d5d70e80136578d3/src/chain.h#L263). I've posted [a question on the Bitcoin stack](https://bitcoin.stackexchange.com/questions/71517/in-what-circumstances-would-a-block-appear-in-the-leveldb-ldb-index-but-have-no) to better understand. It seems to only be occurring for the top few blocks. Maybe block data isn't stored to disk until it is validated `n` times?

**Comment by alecalve** [comment]
I think it could be because the blocks aren't flushed to disk yet. The weird part being that the index entries _are_ flushed.

**Comment by QianchaoLiu** [comment]
My code break out at block 478561, which may be a block near the folk. Anyone know how to figure it out?

**Comment by alecalve** [comment]
Have you tried running the latest master? It broke because of Segwit, which is now supported in master (but not yet released).

**Comment by QianchaoLiu** [comment]
@alecalve yes, it is the latest master. It broke at 478561 cause of `blkIdx.file != -1 and blkIdx.data_pos != -1`, so I thought it may be related with this request.

**Comment by brannondorsey** [comment]
Strange, I believe block 478561 was before the Segwit fork. It broke out but did not fail/error, correct? And can you confirm that you have >478561 blocks indexed with `bitcoind`?

**Comment by alecalve** [comment]
SegWit happened at height 481824, however, 478561 is right after the BCH fork. Are you on the correct side of the chain? This library is fully compatible with Bitcoin (Core), but might not work perfectly with altcoins like BCH.

**Comment by QianchaoLiu** [comment]
@alecalve @brannondorsey  Thanks. The problem is caused by my full node. After updating bitcoind to v0.16 and re-download the data, it works well.

**Pull request merged**
