### PR TITLE
Fix Blockchain.get_ordered_blocks(...) bug

### PR DESCRIPTION
**Pull request by brannondorsey**
Somehow, when developing the fix in https://github.com/alecalve/python-bitcoin-blockchain-parser/pull/28, my virtualenv was accidentally configured to use Python2 instead of Python3. Not realizing this, the changes in that PR were written for Python 2.7 and ~~yielded~~ did not yield ordered blocks when run with Python 3.x (surprised it worked at all w/ 2.7 actually). I've reverted to @asutoshpalai original method of parsing the leveldb key/value pairs. This should now work with Python 3.x.

### CODE REVIEW

**Comment by alecalve** [comment]
We should add a test for this (I myself am guilty of not testing this before merging)

**Comment by brannondorsey** [comment]
I too am shamefully guilty of merging PRs from contributors to my own repos without testing them. Sorry for requiring a second PR w/ this issue ;P.  

Writing tests is a good idea, but I myself don't have much experience with writing formal tests. I've been testing informally with this snippet:

```python
import sys
sys.path.append('..')
import os

from blockchain_parser.blockchain import Blockchain

blockchain = Blockchain(sys.argv[1])

last_height = -1
prev_block_hash = None

for block in blockchain.get_ordered_blocks(os.path.join(sys.argv[1], 'index')):
    print(block)
    if last_height != -1 and prev_block_hash != None:
        assert(last_height == block.height - 1)
        assert(block.header.previous_block_hash == prev_block_hash)

    prev_block_hash == block.hash
    last_height += 1
```

**Comment by alecalve** [comment]
It's perfectly fine for me that we merged this early. http://hintjens.com/blog:106 has a good rationale for early merging IMO. I'll create an issue to add tests for this bit so that we do not forget about it.

**Comment by brannondorsey** [comment]
I like that rationale for merging early. Bookmarked and noted, thanks for sharing.

**Pull request merged**
